import Link from "next/link";
import { ArrowLeft, BriefcaseBusiness, CircleAlert, Pencil, Trash2 } from "lucide-react";
import { notFound } from "next/navigation";
import PageHeader from "@/components/PageHeader";
import { StatusBadge } from "@/components/Badge";
import Modal from "@/components/Modal";
import { getDepartments, getEmployeeDetail, type EmployeeDetail } from "@/lib/repositories/employee-repository";
import { removeEmployeeCompletion, removeEmploymentHistory, saveEmployeeCompletion, saveEmploymentHistory, updateEmployee } from "../actions";

export const dynamic = "force-dynamic";

function CompletionHistoryEditor({ employee }: { employee: EmployeeDetail }) {
  return <Modal title="교육 수료 이력 관리" triggerLabel="편집"><form action={saveEmployeeCompletion} className="inline-form"><input type="hidden" name="employee_id" value={employee.id} /><select name="session_id" required defaultValue=""><option value="">교육 차수 선택</option>{employee.sessionOptions.map((session) => <option key={session.sessionId} value={session.sessionId}>{session.courseName} · {session.round}</option>)}</select><select name="status" defaultValue="completed"><option value="completed">수료</option><option value="failed">미수료</option><option value="absent">불참</option><option value="cancelled">취소</option></select><input type="date" name="completion_date" defaultValue={new Date().toISOString().slice(0, 10)} /><button type="submit" className="btn-primary">이력 추가</button></form><div className="summary-list">{employee.completions.length ? employee.completions.map((completion) => <div key={completion.completionId}><span><strong>{completion.courseName} · {completion.round}</strong><small>{completion.status === "completed" ? "수료" : "미수료"} · {completion.completionDate ?? "-"}</small></span><form action={removeEmployeeCompletion}><input type="hidden" name="employee_id" value={employee.id} /><input type="hidden" name="completion_id" value={completion.completionId} /><button type="submit" className="icon-link text-red-600" title="수료 이력 삭제"><Trash2 size={15} /></button></form></div>) : <div className="empty-state">수료 이력이 없습니다.</div>}</div></Modal>;
}

function EmploymentHistoryEditor({ employee, departments }: { employee: EmployeeDetail; departments: { department_id: number; name: string }[] }) {
  return <Modal title="부서 근무 이력 관리" triggerLabel="편집"><form action={saveEmploymentHistory} className="form-grid mb-6"><input type="hidden" name="employee_id" value={employee.id} /><label>부서<select name="department_id" required defaultValue=""><option value="">부서 선택</option>{departments.map((department) => <option key={department.department_id} value={department.department_id}>{department.name}</option>)}</select></label><label>직급<input name="position" /></label><label>시작일<input type="date" name="start_date" required /></label><label>종료일<input type="date" name="end_date" /></label><label className="md:col-span-2">사유<input name="reason" placeholder="부서 이동, 승진 등" /></label><button className="btn-primary md:col-span-2" type="submit">이력 추가</button></form><div className="summary-list">{employee.departmentHistory.length ? employee.departmentHistory.map((history) => { const departmentId = departments.find((department) => department.name === history.departmentName)?.department_id; return <div key={history.historyId}><form action={saveEmploymentHistory} className="form-grid"><input type="hidden" name="employee_id" value={employee.id} /><input type="hidden" name="history_id" value={history.historyId} /><label>부서<select name="department_id" defaultValue={departmentId ?? ""}>{departments.map((department) => <option key={department.department_id} value={department.department_id}>{department.name}</option>)}</select></label><label>직급<input name="position" defaultValue={history.position ?? ""} /></label><label>시작일<input type="date" name="start_date" defaultValue={history.startDate} /></label><label>종료일<input type="date" name="end_date" defaultValue={history.endDate ?? ""} /></label><label className="md:col-span-2">사유<input name="reason" defaultValue={history.reason ?? ""} /></label><div className="flex gap-2 md:col-span-2"><button className="btn-secondary" type="submit">이력 수정</button><button className="icon-link text-red-600" formAction={removeEmploymentHistory} type="submit" title="부서 이력 삭제"><Trash2 size={15} /></button></div></form></div>; }) : <div className="empty-state">부서 근무 이력이 없습니다.</div>}</div></Modal>;
}

export default async function EmployeeDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ edit?: string; error?: string }> }) {
  const { id } = await params;
  const employeeId = Number(id);
  const query = await searchParams;
  const employee = await getEmployeeDetail(employeeId);
  if (!employee) notFound();
  const detail = employee as EmployeeDetail;
  const departments = await getDepartments();
  return <div><PageHeader title={detail.name} description={`${detail.employeeNumber} · ${detail.departmentName}`} action={<div className="flex items-center gap-2"><Link href="/employees" className="btn-secondary flex items-center gap-2"><ArrowLeft size={14} /> 직원 목록</Link>{query.edit === "1" ? null : <Link href={`/employees/${detail.id}?edit=1`} className="btn-primary flex items-center gap-2"><Pencil size={14} /> 편집</Link>}</div>} /><div className="page-content space-y-6">{query.error ? <div className="notice warning">{query.error}</div> : null}{query.edit === "1" ? <section className="card p-6"><form action={updateEmployee} className="form-grid"><input type="hidden" name="employee_id" value={detail.id} /><label>이름<input name="name" defaultValue={detail.name} required /></label><label>사번<input name="employee_number" defaultValue={detail.employeeNumber} inputMode="numeric" pattern="[0-9]{10}" maxLength={10} required /></label><label>입사일<input type="date" name="hire_date" defaultValue={detail.hireDate === "-" ? "" : detail.hireDate} required /></label><label>부서<select name="department" defaultValue={detail.departmentName} required>{departments.map((department) => <option key={department.department_id} value={department.name}>{department.name}</option>)}</select></label><label>직급<input name="position" defaultValue={detail.position === "미등록" ? "" : detail.position} /></label><label>상태<select name="status" defaultValue={detail.status} required><option>재직</option><option>휴직</option><option>퇴사</option></select></label><label className="md:col-span-2">이메일<input type="email" name="email" defaultValue={detail.email ?? ""} /></label><div className="flex gap-2 md:col-span-2"><button className="btn-primary" type="submit">저장</button><Link className="btn-secondary" href={`/employees/${detail.id}`}>취소</Link></div></form></section> : <section className="profile-hero card"><span className="profile-avatar">{detail.name.slice(-2)}</span><div className="profile-name"><div className="flex items-center gap-2"><h2>{detail.name}</h2><StatusBadge status={detail.status} /></div><p>{detail.position} · {detail.departmentName}</p></div><div className="profile-facts"><div><small>현재 부서</small><strong>{detail.departmentName}</strong></div><div><small>입사일</small><strong>{detail.hireDate}</strong></div><div><small>이메일</small><strong>{detail.email ?? "-"}</strong></div></div></section>}
      <div className="two-column"><section className="card p-6"><div className="section-heading panel-heading"><div><span className="eyebrow">TRAINING</span><h2>교육 수료 이력</h2></div><CompletionHistoryEditor employee={detail} /></div><div className="summary-list">{detail.completions.slice(0, 3).map((completion) => <div key={completion.completionId}><strong>{completion.courseName} · {completion.round}</strong><small>{completion.status === "completed" ? "수료" : "미수료"} · {completion.completionDate ?? "-"}</small></div>)}</div><p className="muted">전체 {detail.completions.length}건</p></section><section className="card p-6"><div className="section-heading panel-heading"><div><span className="eyebrow">CAREER</span><h2>부서 근무 이력</h2></div><EmploymentHistoryEditor employee={detail} departments={departments} /></div><div className="summary-list">{detail.departmentHistory.slice(0, 3).map((history) => <div key={history.historyId}><strong>{history.departmentName}</strong><small>{history.position ?? "-"} · {history.startDate} — {history.endDate ?? "현재"}</small></div>)}</div><p className="muted">전체 {detail.departmentHistory.length}건</p></section></div>
      <section className="card p-6"><div className="section-heading panel-heading"><div><span className="eyebrow">REQUIRED</span><h2>현재 미수료 대상 과정</h2></div><CircleAlert size={19} /></div>{detail.incompleteCourses.length ? <div className="summary-list">{detail.incompleteCourses.slice(0, 5).map((course) => <div key={course.courseId}><strong>{course.courseName}</strong><span className="status-pill warning">미수료</span></div>)}</div> : <div className="empty-state">현재 미수료 대상 과정이 없습니다.</div>}</section>
      <section className="card"><div className="section-heading panel-heading"><div><span className="eyebrow">NOTICE</span><h2>안내</h2></div><BriefcaseBusiness size={19} /></div><p className="muted">교육 수료 이력과 부서 근무 이력은 각각 팝업의 편집 버튼에서 관리할 수 있습니다.</p></section>
    </div></div>;
}
